<?php
ob_start();
date_default_timezone_set('America/New_York');
require_once('includes/tcpdf/tcpdf.php');
require_once('includes/tcpdf/config/tcpdf_config.php');

// extend TCPF with custom functions
class MYPDF extends TCPDF {
    //Eventually these will be populated with data (Heading include: Header, Short description of the report, Generation Source, Generation Date)
    public function heading() {
        $html = <<<EOD
		<!DOCTYPE html>
		<head>
			<!-- Bootstrap core CSS -->
			<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
			<link rel="stylesheet" href="../../css/callouts.css">
			<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
			<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
		</head>
        <h1 style="text-align:Center;">Sales Report</h1>
        <h2 style="text-align:right;font-size:60%;">Generated by Lightning Sales Processor<br>Date Generated: XX/XX/XXXX</span>
        <p style="font-size:80%;">This report was generated by the lightning Sales processor it contains information for books sold in X categories across X amount of time<p>
EOD;
        $this->writeHTMLCell(0, 0, '', '', $html, 0, 1, 0, true, '', true);
    }
    public function table($header, $data) {
        //Set color and font for the table
        $this->SetFillColor(255, 255, 255);
        $this->SetTextColor(0);
        $this->SetDrawColor(0, 0, 0);
        $this->SetLineWidth(0.2);
        $this->SetFont('times', 'B', 10);

        //Create Header for the table
        $w = array(25, 25, 25, 25, 25);
        $num_headers = count($header);
        $this->Cell($w[0], 7, $header[0], '', 0, 'C',1);
        for($i = 1; $i < $num_headers; ++$i) {
            $this->Cell($w[$i], 7, $header[$i], 1, 0, 'C', 1);
        }
        $this->Ln();
        // Set Color and font for table data
        $this->SetFillColor(255, 255, 255);
        $this->SetTextColor(0);

        //Populate stored data
        $fill = 0;
        foreach($data as $row) {
            $this->SetFont('times', '', 10);
            $this->Cell($w[0], 6, $row[0], 0, 0, '', $fill);
            $this->SetFont('times', '', 8);
            $this->Cell($w[1], 6, $row[1], 'LTRB', 0, 'L', $fill);
            $this->Cell($w[2], 6, $row[2], 'LTRB', 0, 'L', $fill);
            $this->Cell($w[3], 6, $row[3], 'LTRB', 0, 'L', $fill);
            $this->Cell($w[4], 6, $row[4], 'LTRB', 0, 'L', $fill);
            $this->Ln();
            $fill=!$fill;
        }
        //$this->Cell(array_sum($w), 0, '', 'T');
    }
}

// create new PDF document
$pdf = new MYPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);


// set document information
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('Lightning Sales Processor');
$pdf->SetTitle('Sales Report');
$pdf->SetSubject('Generated Reports');
$pdf->SetKeywords('reports, generation, sales, employees, summarization');

// remove default header/footer
$pdf->setPrintHeader(false);
$pdf->setPrintFooter(false);

// set header and footer fonts
$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

// set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

// set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

// set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

// set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

// set some language-dependent strings (optional)
if (@file_exists(dirname(__FILE__).'/lang/eng.php')) {
    require_once(dirname(__FILE__).'/lang/eng.php');
    $pdf->setLanguageArray($l);
}

// ---------------------------------------------------------

// set font and default font subsetting mode
$pdf->setFontSubsetting(true);
$pdf->SetFont('times', '', 12, '', true);

//Add page to the pdf
$pdf->AddPage();

// set text shadow effect
$pdf->setTextShadow(array('enabled'=>true, 'depth_w'=>0.2, 'depth_h'=>0.2, 'color'=>array(196,196,196), 'opacity'=>1, 'blend_mode'=>'Normal'));

//Example table populating data
$header = array('','Initial Inventory', 'Quantity Sold', 'Price', 'Total (Gross)');

//Function calls to format the report
$pdf->heading();
$pdf->table($header, $data);


// Close and output PDF document
// This method has several options, check the source code documentation for more information.
$pdf->Output('report.pdf', 'I');

?>