<!DOCTYPE html>
<form role="form" id="gen_form" action="generated_print.php" method="POST">
	<input type="hidden" id="html_report" value=""/>
</form>

<?php
ob_start();
date_default_timezone_set('America/New_York');
require_once('includes/tcpdf/tcpdf.php');
require_once('includes/tcpdf/config/tcpdf_config.php');
require_once('../includes/database.php');
require_once('printables_process_table_functions.php');

// create new PDF document
$pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
// set document information
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('Lightning Sales Processor');
$pdf->SetTitle('Sales Report');
$pdf->SetSubject('Generated Reports');
$pdf->SetKeywords('reports, generation, sales, employees, summarization');
// remove default header/footer
$pdf->setPrintHeader(false);
$pdf->setPrintFooter(false);
//set header and footer fonts
$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));
// set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);
// set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);
// set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);
// set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);
// set some language-dependent strings (optional)
if (@file_exists(dirname(__FILE__).'/lang/eng.php')) {
    require_once(dirname(__FILE__).'/lang/eng.php');
    $pdf->setLanguageArray($l);
}
// set font and default font subsetting mode
$pdf->setFontSubsetting(true);
$pdf->SetFont('times', '', 12, '', true);
//Add page to the pdf
$pdf->AddPage();
// set text shadow effect
$pdf->setTextShadow(array('enabled'=>true, 'depth_w'=>0.2, 'depth_h'=>0.2, 'color'=>array(196,196,196), 'opacity'=>1, 'blend_mode'=>'Normal'));


//---------------BEGIN FORMATTING THE PAGE-------------------------------
//Bring in POST Information
$reporttype = $_POST['whichreport'];
$reportduration = $_POST['ReportDuration'];
$sd = $_POST['date'];
$ed;
$startdate = explode("/", $_POST['date']);
$columns = array();
$numDays = 0;
//get columns
foreach ($_POST['ProductTypeSelected'] as $column){
	array_push($columns, $column);
}
//header
$generate_date = date("Y-m-d");
$header = '<!DOCTYPE html><h1 style="text-align:Center;">Sales Report</h1><h2 style="text-align:right;font-size:60%;">Generated by Lightning Sales Processor<br>Date Generated:' . $generate_date .'</h2><p style="font-size:80%;">This report was automatically generated by the Lightning Sales Processor software system it contains information for books sold in the following categories';

for ($i = 0; $i < count($columns); $i++) {
	$header = $header . ', ' . $columns[$i];
}
$html;
if ($reportduration == "daily") {
	$numDays = 1;
}else if ($reportduration == "weekly"){
	$numDays = 7;
	//append 7 day date duration
	$day = (intval($startdate[1]) + 6);
	$ted = (string) $day;
	if (intval($day) < 10) $ted = "0" . $ted;
	$ed = $startdate[0] ."/" . $ted . "/" . $startdate[1];
	$header = $header . ' across the following time period: ' . $sd . '-' . $ed . '</p>';
}else if ($reportduration == "quarterly"){
	$numDays = 0;
}

//get complete duration values
$complete_num_sales = array_pad(array(), $numDays, 0);
$complete_sales = array_pad(array(), $numDays, 0); //Represents grand total sales for a single day
$complete_sales_percent = array_pad(array(), $numDays, 0);
$complete_grand_total; //represents grand total sales for the entire week
$all_weekdays = array();


for ($i = 0; $i < $numDays; $i++) {
	//Format the query for a selected day
	$qry = "SELECT Genre, LineItemTotal, `Timestamp`, Status FROM Transactions LEFT JOIN Products ON Transactions.ProductID=Products.ProductID WHERE (";
	foreach ($_POST['ProductTypeSelected'] as $column){
		$qry = $qry . "Products.Genre='" . $column . "' OR ";
	}
	$qry = chop($qry, " OR ");
	$startday = (string) (intval($startdate[1]) + $i);
	if ($startday < 10) $startday = "0" . $startday;
	$qry = $qry . ") and (`Timestamp` BETWEEN '{$startdate[2]}-{$startdate[0]}-{$startday} 00:00:00' and '{$startdate[2]}-{$startdate[0]}-{$startday} 11:59:59')";
	//Get the queried information
	$result = mysqli_query($link, $qry);
	$rows = mysqli_fetch_all($result, MYSQLI_BOTH);
	
	//Get num sales, total sales, sales_percent
	$num_sales = array_pad(array(), count($columns), 0);
	$total_sales = array_pad(array(), count($columns), 0);
	$sales_percent = array_pad(array(), count($columns), 0);
	$grand_total = 0;
	for($r = 0; $r < mysqli_num_rows($result); $r++) {
		$row = $rows[$r];
		for ($r2 = 0; $r2 < count($columns); $r2++) {
			if ($row['Genre'] == $columns[$r2]) {
				$num_sales[$r2]++;
				$total_sales[$r2] += intval($row['LineItemTotal']);
				
				$complete_num_sales[$i] += $num_sales[$r2];
			}
		}
		$grand_total += intval($row['LineItemTotal']);
	}
	$complete_sales[$i] += $grand_total;
	for($j = 0; $j < count($columns); $j++) {
		if ($grand_total != 0) {
			$sales_percent[$j] = round($total_sales[$j] / $grand_total, 2);
		}
	}
	$in = $startdate[2] . '-' . $startdate[0] .'-' .$startday;
	$weekday = date("l", strtotime($in));
	$all_weekdays[$i] = $weekday;
	$html = $html . daily_table($columns, $total_sales, $sales_percent, $num_sales, $weekday);
}

if ($reportduration == "weekly") {
	//calculate complete sales for the week
	for ($i = 0; $i < 7; $i++) { 
		$complete_grand_total += $complete_sales[$i];
	}
	//get the percentage of sales for each weekdays
	for($i = 0; $i < 7; $i++) {
		if ($complete_sales[$i] != 0) {
			$complete_sales_percent[$i] = round($complete_sales[$i] / $complete_grand_total, 2);
		}
	}
	$complete_grand_total += $grand_total;
	$html = week_table($complete_sales, $complete_sales_percent, $complete_num_sales, $sd, $ed, $all_weekdays) . $html;
}
$html = $header . $html;
$pdf->writeHTMLCell(0, 0, '', '', $html, 0, 1, 0, true, '', true);
// Close and output PDF document
ob_end_clean();
$view = $_POST['viewtype'];
if ($view == "pdf") {
}else if ($view == "dpdf"){
	$pdf->Output('report.pdf', 'D');
}else if ($view == "webpage") {
	echo $html;
}

?>