<?php
ob_start();
date_default_timezone_set('America/New_York');
require_once('../includes/tcpdf/tcpdf.php');
require_once('../includes/tcpdf/config/tcpdf_config.php');
require_once('../../includes/database.php');
require_once('printables_process_table_functions.php');
//create new PDF document
$pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
// set document information
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('Lightning Sales Processor');
$pdf->SetTitle('Sales Report');
$pdf->SetSubject('Generated Reports');
$pdf->SetKeywords('reports, generation, sales, employees, summarization');
// remove default header/footer
$pdf->setPrintHeader(false);
$pdf->setPrintFooter(false);
//set header and footer fonts
$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));
// set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);
// set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);
// set auto page breaks
$pdf->SetAutoPageBreak(FALSE, PDF_MARGIN_BOTTOM);
// set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);
// set some language-dependent strings (optional)
if (@file_exists(dirname(__FILE__).'/lang/eng.php')) {
    require_once(dirname(__FILE__).'/lang/eng.php');
    $pdf->setLanguageArray($l);
}
// set font and default font subsetting mode
$pdf->setFontSubsetting(true);
$pdf->SetFont('times', '', 12, '', true);
//Add page to the pdf
$pdf->AddPage();
// set text shadow effect
$pdf->setTextShadow(array('enabled'=>true, 'depth_w'=>0.2, 'depth_h'=>0.2, 'color'=>array(196,196,196), 'opacity'=>1, 'blend_mode'=>'Normal'));


//---------------BEGIN FORMATTING THE PAGE-------------------------------
//Bring in POST Information
$lowStock = 50;
global $link;
//header
$generate_date = date("Y-m-d");
$header = '<!DOCTYPE html><h1 style="text-align:Center;">Stock Report</h1><h2 style="text-align:right;font-size:60%">Generated by Lightning Sales Processor<br>Date Generated:' . $generate_date .'</h2><p style="font-size:80%">This report was automatically generated by the Lightning Sales Processor software system it contains information on employee performance. It list the stores product information and current status.</p>';
$html;

//get ids of all the employees;
$qryProd = "SELECT ProductName, Genre, Stock FROM Products ORDER BY STOCK ASC";
$result = mysqli_query($link, $qryProd);
$numProds = mysqli_num_rows($result);

//create arrays for individual transactions
$p_names = array();
$genres = array();
$stocks = array();

//fill arrays with individual transactions
for ($j = 0; $j < $numProds; $j++) {
	$row = mysqli_fetch_assoc($result);
	array_push($p_names, $row['ProductName']);
	array_push($genres, $row['Genre']);
	array_push($stocks, $row['Stock']);
}
//sends transactions to be written to html
$html = $html . low_stock($p_names, $genres, $stocks, $numProds, $lowStock);
$html = $header . $html;

$pdf->writeHTMLCell(0, 0, '', '', $html, 0, 1, 0, true, '', true);

//Close and output PDF document or write to webpage
ob_end_clean();
$view = $_POST['viewtype'];
if ($view == "pdf") {
	$pdf->Output('report.pdf', 'I');
}else if ($view == "dpdf"){
	$pdf->Output('report.pdf', 'D');
}else if ($view == "webpage") {
	echo $html;
}
?>