<?php
ob_start();
date_default_timezone_set('America/New_York');
require_once('../includes/tcpdf/tcpdf.php');
require_once('../includes/tcpdf/config/tcpdf_config.php');
require_once('../../includes/database.php');
require_once('printables_process_table_functions.php');
//create new PDF document
$pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
// set document information
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('Lightning Sales Processor');
$pdf->SetTitle('Sales Report');
$pdf->SetSubject('Generated Reports');
$pdf->SetKeywords('reports, generation, sales, employees, summarization');
// remove default header/footer
$pdf->setPrintHeader(false);
$pdf->setPrintFooter(false);
//set header and footer fonts
$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));
// set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);
// set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);
// set auto page breaks
$pdf->SetAutoPageBreak(FALSE, PDF_MARGIN_BOTTOM);
// set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);
// set some language-dependent strings (optional)
if (@file_exists(dirname(__FILE__).'/lang/eng.php')) {
    require_once(dirname(__FILE__).'/lang/eng.php');
    $pdf->setLanguageArray($l);
}
// set font and default font subsetting mode
$pdf->setFontSubsetting(true);
$pdf->SetFont('times', '', 12, '', true);
//Add page to the pdf
$pdf->AddPage();
// set text shadow effect
$pdf->setTextShadow(array('enabled'=>true, 'depth_w'=>0.2, 'depth_h'=>0.2, 'color'=>array(196,196,196), 'opacity'=>1, 'blend_mode'=>'Normal'));


//---------------BEGIN FORMATTING THE PAGE-------------------------------
//Bring in POST Information
$reporttype = $_POST['whichreport'];
$reportduration = $_POST['ReportDuration'];
$gen_man = "";
$prod_man = "";
$b_sell = "";
if(isset($_POST['general_manager'])) $gen_man = $_POST['general_manager'];
if(isset($_POST['product_manager'])) $prod_man = $_POST['product_manager'];
if(isset($_POST['book_seller'])) $b_sell = $_POST['book_seller'];

$sd = $_POST['date']; //start date
$ed; //end date
$startdate = explode("/", $_POST['date']);
$columns = array();
$numDays = 0;

//header
$generate_date = date("Y-m-d");
$header = '<!DOCTYPE html><h1 style="text-align:Center;">Employees Report</h1><h2 style="text-align:right;font-size:60%">Generated by Lightning Sales Processor<br>Date Generated:' . $generate_date .'</h2><p style="font-size:80%">This report was automatically generated by the Lightning Sales Processor software system it contains information on employee performance. It list the amount of orders they have taken within a given time period and their current statuses.</p>';

for ($i = 0; $i < count($columns); $i++) {
	$header = $header . ', ' . $columns[$i];
}
$html;
if ($reportduration == "daily") {
	$numDays = 1;
}else if ($reportduration == "weekly"){
	$numDays = 7;
	$day = (intval($startdate[1]) + 6);
	$ted = (string) $day;
	if (intval($day) < 10) $ted = "0" . $ted;
	$ed = $startdate[0] ."/" . $ted . "/" . $startdate[1]; //final enddate
}else if ($reportduration == "quarterly"){
	$numDays = 0;
}
//get ids of all the employees;
$qryEmployees = "SELECT EmployeeID, FirstName, LastName, Role FROM Employees WHERE ";
if ($gen_man == "general_manager") $qryEmployees = $qryEmployees . "Role=1 OR ";
if ($prod_man == "product_manager") $qryEmployees = $qryEmployees . "Role=2 OR ";
if ($b_sell == "book_seller") $qryEmployees = $qryEmployees . "Role=3 OR ";
$qryEmployees = chop($qryEmployees, " OR ");
$res = mysqli_query($link, $qryEmployees);
$emp = mysqli_fetch_all($res, MYSQLI_BOTH);

$emp_name = array();
$emp_ids = array();
for ($i = 0; $i < mysqli_num_rows($res); $i++) {
	$row = $emp[$i];
	array_push($emp_ids, $row['EmployeeID']);
	array_push($emp_name, ($row['FirstName'] . " " .$row['LastName']));
}

//Gets a collection of transactions handled buy a specific employee
$trans = array();
$qrys = array();
$qryTrans;
for ($i = 0; $i < count($emp_ids); $i++) {
	$startday = (string) (intval($startdate[1]));
	$endday = (string) (intval ($startdate[1]) + ($numDays - 1));
	$curTime = date("H:i:s");
	$today = date("Y-m-d");
	if (($startdate[2] . "-" . $startdate[0] . "-" . $endday) == ((string) $today)) {
		$qryTrans = "SELECT TransactionID, GROUP_CONCAT(Quantity), GROUP_CONCAT(LineItemTotal), Status, DeliveryType FROM Transactions WHERE (EmployeeID = {$emp_ids[$i]} ) and (`Timestamp` BETWEEN '{$startdate[2]}-{$startdate[0]}-{$startday} 00:00:00' and '{$startdate[2]}-{$startdate[0]}-{$endday} {$curTime}') GROUP BY TransactionID";
	} else {
		$qryTrans = "SELECT TransactionID, GROUP_CONCAT(Quantity), GROUP_CONCAT(LineItemTotal), Status, DeliveryType FROM Transactions WHERE (EmployeeID = {$emp_ids[$i]} ) and (`Timestamp` BETWEEN '{$startdate[2]}-{$startdate[0]}-{$startday} 00:00:00' and '{$startdate[2]}-{$startdate[0]}-{$endday} 11:59:59') GROUP BY TransactionID";
	}
	$res = mysqli_query($link, $qryTrans);
	array_push($trans, $res);
	array_push($qrys, $qryTrans);
}
//Writes out transactions to html
$html = $html . '<table cellspacing="0" cellpadding="0" border="1">';
$html = $html . '<tr style="text-weight:bold;color:#003d99"><td>Employee</td><td>ID</td><td>Quantity</td><td>Sale Total</td><td>Status</td><td>Delivery Type</td></tr>';
for ($i = 0; $i < count($emp_ids); $i++) {
	//create arrays for individual transactions
	$tids = array();
	$quant = array();
	$totals = array();
	$stat = array();
	$dtype = array();
	
	
	//fill arrays with individual transactions
	for ($j = 0; $j < mysqli_num_rows($trans[$i]); $j++) {
		$row = mysqli_fetch_assoc($trans[$i]);
		array_push($tids, $row['TransactionID']);
		array_push($quant, array_sum( array_map("intval", explode(",", $row['GROUP_CONCAT(Quantity)'])) ));
		array_push($totals, array_sum( array_map("floatval", explode(",", $row['GROUP_CONCAT(LineItemTotal)'])) ));
		array_push($stat, $row['Status']);
		array_push($dtype, $row['DeliveryType']);
	}
	//sends transactions to be written to html
	$html = $html . employees_table($emp_name[$i], $tids, $quant, $totals, $stat, $dtype, mysqli_num_rows($trans[$i]));
}
$html = $html . "</table>";

if ($reportduration == "weekly") {	
}
$html = $header . $html;
$pdf->writeHTMLCell(0, 0, '', '', $html, 0, 1, 0, true, '', true);

//Close and output PDF document or write to webpage
ob_end_clean();
$view = $_POST['viewtype'];
if ($view == "pdf") {
	$pdf->Output('report.pdf', 'I');
}else if ($view == "dpdf"){
	$pdf->Output('report.pdf', 'D');
}else if ($view == "webpage") {
	echo $html;
}
?>